skip_docs

lane :generate do
  require 'fileutils'
  tools = %w(fastlane fastlane_core deliver snapshot frameit pem sigh produce cert gym pilot credentials_manager spaceship scan supply match screengrab precheck)
  manual_mapping = {
    "fastlane" => "https://docs.fastlane.tools",
    "spaceship" => "https://github.com/fastlane/fastlane/blob/master/spaceship/README.md#readme",
    "fastlane_core" => "https://github.com/fastlane/fastlane/tree/master/fastlane_core#readme",
    "credentials_manager" => "https://github.com/fastlane/fastlane/tree/master/credentials_manager#readme"
  }
  puts "Generating short links for: \n#{tools.join(', ')}"

  Dir.chdir("..") do
    tools.each do |current|
      FileUtils.mkdir(current) unless File.directory?(current)

      url = "https://docs.fastlane.tools/actions/#{current}"
      if manual_mapping[current].to_s.length > 0
        url = manual_mapping[current]
      end

      index = <<-eos
  <script type=\"text/javascript\">
    location.href = \"#{url}\"
  </script>
  eos

      File.write(File.join(current, "index.html"), index)
    end
  end
end
