name: 'Install'
description: 'Install and pre-build'

runs:
  using: composite
  steps:
    - uses: actions/setup-python@v6
      with:
        python-version-file: ".python-version"

    - uses: actions/setup-node@v6
      with:
        node-version: 24
        cache: 'npm'

    - name: Install uv
      uses: astral-sh/setup-uv@v6

    - name: Install Grow dependencies
      shell: bash
      run: uv run grow install
